### ISSUE TITLE
Game creation error

### ISSUE THREAD

**Issue by giviz** [apsillers/lords-of-the-fey#14]
So now I can login, create a game, but that crash the script 

```
giviz@localhost:~/lords-of-the-fey$ nodejs server.js
body-parser deprecated bodyParser: use individual json/urlencoded middlewares server.js:71:31
successful connection to socket.io
successful connection to socket.io
serving data to hello
successful connection to socket.io
serving data to anon094909
successful connection to socket.io
successful connection to socket.io
/home/giviz/lords-of-the-fey/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Cannot read property '_id' of undefined
    at addCommander (/home/giviz/lords-of-the-fey/createGame.js:99:34)
    at /home/giviz/lords-of-the-fey/createGame.js:111:15
    at /home/giviz/lords-of-the-fey/node_modules/mongodb/lib/collection.js:485:5
    at /home/giviz/lords-of-the-fey/node_modules/mongodb/lib/collection.js:643:5
    at handleCallback (/home/giviz/lords-of-the-fey/node_modules/mongodb/lib/utils.js:96:12)
    at executeCommands (/home/giviz/lords-of-the-fey/node_modules/mongodb/lib/bulk/ordered.js:396:12)
    at resultHandler (/home/giviz/lords-of-the-fey/node_modules/mongodb/lib/bulk/ordered.js:423:5)
    at /home/giviz/lords-of-the-fey/node_modules/mongodb-core/lib/topologies/server.js:780:13
    at Callbacks.emit (/home/giviz/lords-of-the-fey/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at Connection.messageHandler (/home/giviz/lords-of-the-fey/node_modules/mongodb-core/lib/topologies/server.js:249:23)
```

If I reload it and open the game, there is no units on the map.

```
> db.games.find()
{ "_id" : ObjectId("5b1be7536be451f66ddda594"), "map" : "2p_Hornshark_Island.map", "timeOfDay" : "morning", "players" : [ { "username" : "hello", "ready" : true, "faction" : "elves", "team" : 1, "alliance" : 1, "gold" : 100 }, { "username" : "anon094909", "ready" : true, "anonToken" : "09490974830990262", "faction" : "orcs", "team" : 2, "alliance" : 2, "gold" : 102 } ], "villages" : { "8,3" : 0, "1,4" : 0, "17,5" : 0, "14,6" : 0, "27,9" : 0, "16,10" : 0, "4,12" : 0, "21,14" : 0, "26,14" : 0, "10,16" : 0, "16,17" : 0, "7,20" : 0, "18,21" : 0, "19,25" : 0, "23,25" : 0, "30,25" : 0 }, "activeTeam" : 2, "alliances" : { "1" : 1, "2" : 2 } }
{ "_id" : ObjectId("5b1be8c2316fbaae725abf6a"), "map" : "test_map.map", "timeOfDay" : "morning", "players" : [ { "username" : "hello", "ready" : true, "faction" : "elves", "team" : 1, "alliance" : 1, "gold" : 100 }, { "username" : "anon280909", "ready" : true, "anonToken" : "28090996538935165", "faction" : "orcs", "team" : 2, "alliance" : 2, "gold" : 100 }, { "empty" : true } ], "villages" : { "8,3" : 0 }, "activeTeam" : 1, "alliances" : { "1" : 1, "2" : 2 } }
```

Any idea on what can cause that error ?

**Comment by apsillers** [comment]
Looks like this was a Window vs. Linux error -- I couldn't repro it until I switched to my Windows box.

I just pushed a fix that correctly upgrades the Mongo driver to 2.2.x. Let me know if that fixes things in your environment.

Also, I have a (largely untested) demo site again, now at http://lotf--apsillers.repl.co

**Comment by giviz** [comment]
I've tried the demo but impossible to launch a game (we can't select the map).

I've made a clean install on my debian dev machine and the have been able to create and play a game with 2 players :)

Nice work so far !

Do you plan to continue to develop the game up to a fully working state ?
